language: python
python:
  - "3.4"
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libatlas3gf-base
      - libatlas-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests -c nose.cfg
