language: python
python:
  - "3.4"
addons:
  apt:
    packages:
      - libatlas-dev
      - python-scipy
virtualenv:
  system_site_packages: true
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests -c nose.cfg
